### ISSUE TITLE
Deploy check-triggers function

### ISSUE THREAD

**Issue by billingross** [billingross/trellis-v2#20]

**Comment by billingross** [comment]
New database triggers look like this:

```
--- !DatabaseTrigger
name: RelateFastqMatePair
pattern: relationship
start:
    label: PersonalisSequencing
    properties:
        sample: sample
relationship:
    type: GENERATED
end:
    label: Fastq
    properties:
        readGroup: read_group
query: relateFastqMatePair
```

**Comment by billingross** [comment]
New database queries look like this:

```
--- !DatabaseQuery
name: relateFastqMatePair
cypher: 'MATCH (r1:Fastq)<-[:GENERATED]-(seq:PersonalisSequencing)-[:GENERATED]->(r2:Fastq)
  WHERE seq.sample = $sample
  AND r1.readGroup = $read_group
  AND r2.readGroup = $read_group
  AND r1.matePair = 1
  AND r2.matePair = 2
  MERGE (r1)-[rel:HAS_MATE_PAIR]->(r2)
  RETURN r1, rel, r2'
required_parameters:
  sample: str
  read_group: int
write_transaction: true
publish_to:
  - TOPIC_TRIGGERS
job_request: null
indexes:
  PersonalisSequencing:
    - sample
returns:
  -
    start: Fastq
    relationship: HAS_MATE_PAIR
    end: Fastq
aggregate_results: false
redundant: false
```

**Comment by billingross** [comment]
I want to start with relating fastqs to each other because fastqs are the basic objects of genomic analysis. The current model for relating mate pairs to each other is initiated by the `RelateFastqMatePair` trigger which is activated by the following relationship:

```mermaid
graph TD;
PersonalisSequencing--GENERATED-->Fastq
```

This is an issue because it relies on a PersonalisSequencing node which is very specific. All paired-end read fastqs have mate pairs and most of them don't come from Personalis. I don't want my model to be locked into a sequencing vendor.

Here is my previous conception of a Trellis workflow
- New object is added to Cloud Storage
- Trellis creates a node to represent that object
- Trellis relates that node to the node that generated it
- Trellis uses that relationship to perform downstream operations

The logic there, as I remember it, was that I want to control the order of operations so that triggers are not being repeatedly activated. But I also think triggers should be designed so that they activate when their minimum requirements are met. As soon as a paired-end Fastq is added to the database, it can and should immediately look for its mate pair.

**Comment by billingross** [comment]
Database triggers can be activated by nodes or single relationships. Here is an example of a trigger that is activated by a node:

```
--- !DatabaseTrigger
name: MergeBiologicalNodes
pattern: node
start: 
    label: PersonalisSequencing
    properties:
        sample: sample
query: mergeBiologicalNodes
```

Node triggers simply omit the elements of a relationship trigger (`relationship` and `end`) and keep the `start` property.
