### ISSUE TITLE
Deploy job-launcher

### ISSUE THREAD

**Issue by billingross** [billingross/trellis-v2#26]
- [x] Deploy job-launcher function
- [x] Create trellis-job-launcher topic
- [x] Update job request query to also create connections to inputs
- [x] Simplify `job-launcher.py` logic and configuration file to get job parameters from `JobRequest` node and get all dsub parameters from configuration file
- [x] Create separate configuration files for each job
- [x] Update `fastq-to-ubam.sh` script to handle a list of inputs generate from pattern matching rather than single values (scratched - I don't want to complicate things. I think it'll work as-is as long as inputs are correct
- [x] Use a separate script to store the command to run each job
- [x] Test new `job-launcher.py` logic with `fastq-to-ubam

**Comment by billingross** [comment]
# How do I handle different types of inputs?

- `fastq-to-ubam` takes two related nodes as input
- `launch-gatk` takes a variable set of nodes as input that are not directly related
- In all cases I also want to take a job-request node as input

So I could have a unified model of getting job inputs that looks like 

```mermaid
graph TD;
ReadGroup--TRIGGERED-->JobRequest
ReadGroup--HAS_FASTQ-->Fastq1
ReadGroup--HAS_FASTQ-->Fastq2
Fastq1--HAS_MATE_PAIR-->Fastq2
```

Actually, it doesn't matter how the query is structured because all the relationships will be returned independently.

So, this is what my `!JobLauncher` inputs look like right now:

```
inputs:
  nodes:
  relationship:
    start: Fastq
    type: HAS_MATE_PAIR
    end: Fastq
```

With the idea being that you either have one set of input nodes (not implemented) or you have one relationship model. The `start`, `type`, `end` model should be consistent so that the `job-launcher.py` logic can be consistent.

**Comment by billingross** [comment]
What if I also add names to each type of `node` and `relationship` so that I can specify multiple types. For example:

```
inputs:
  nodes:
    name: job-request
    start: JobRequest
  relationships:
    name: mate-pair
    start: Fastq
    type: HAS_MATE_PAIR
    end: Fastq
```

And then how would I store that

```
nodes = {
                 'job-request': [
                                          {'start':<node>}
                 ]
}
relationships = {
                           'mate-pair': [
                                {'start':<node>, 'end': <node>}
                           ]
}
```

**Comment by billingross** [comment]
That feels extremely fucking hairy. A dictionary inside a list inside a dictionary.

**Comment by billingross** [comment]
What are the use cases I want to account for?

- [ ] Single node provided as input
- [ ] Single relationship being provided as input
- [ ] Multiple instances of the same type of node/relationship being provided as input
- [ ] Multiple nodes and relationships being provided as input

Example GATK input:
```mermaid
graph TD;
Sample--HAS-->ReadGroup0
Sample--HAS-->ReadGroup1
ReadGroup0--HAS-->Ubam0
ReadGroup1--HAS-->Ubam1
Sample--HAS-->JobRequest
```

Let's just say no unconnected nodes as inputs:

```
inputs:
  relationships:
    -
      name: mate-pair
      start: ReadGroup
      type: HAS_UBAM
      end: Ubam
    -
      name: job-request
      start: Sample
      type: TRIGGERED
      end: JobRequest
```
