### ISSUE TITLE
How to name file paths on cloud storage?

### ISSUE THREAD

**Issue by billingross** [billingross/trellis-v2#33]
Previously, I name objects according to their provenance, meaning that the object path indicated how the object was created. Now, I want to store the objects in a way that they can be used functionally. One way I can think of doing this is by tracking provenance as object metadata and functional use in the object name.

```
name: sample0/HAS_READ_GROUP/0/HAS_PAIRED_END_FASTQ/fastq_0_R1.fastq.gz
metadata: {
  trellisTaskId: 240426-215012-691-4bfa22bf
  trellisTaskName: fastq-to-ubam
  trellisTaskLabel: fq2u-4bfa2
  inputs: 3,0
  image: gcr.io/trellis-v2/broadinstitute/gatk:4.1.0.0
}
```

This way every object can describe its own provenance as well as its functionality even without a database connection and conversely all of the database connections can be reconstituted from the object.

**Comment by billingross** [comment]
Functionally, how do I implement this since most task managers don't include a mechanism for handling object metadata directly?

I could first name the objects according to their provenance, update their metadata, and then rename them according to functionality.

1. Create object
```
gs://storage-bucket/trellis-task-id/GENERATED/sample0_readGroup0.ubam
```
2. Add object to database

```mermaid
graph TD;
Ubam
```
3. Relate object to job

```mermaid
graph TD;
Job--GENERATED-->Ubam
```
4. Add job metadata to object

```
--- !DatabaseTrigger
name: LaunchAddDsubJobMetadataToUbam
pattern: relationship
start:
    label: DsubJob
    properties:
        trellisTaskId
relationship:
    type: Generated
end:
    label: Ubam
query: launchAddJobMetadataToObject
```
